<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Istri  Suami_nama_istri</name>
   <tag></tag>
   <elementGuidId>b53d032b-4f70-4aab-9cc0-d97b241b9fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_istri</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama_istri']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30031f11-2a51-4457-80ca-1da0c5043c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>69ac30cf-e972-4d66-a264-d6b90ca3c294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_istri</value>
      <webElementGuid>c22e98c0-e6e8-4c76-887c-bbb120c32bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_istri</value>
      <webElementGuid>8252086d-73d4-42c8-8c43-2c9b2c5b1035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Istri</value>
      <webElementGuid>cede84b3-e583-4777-a72b-36a007d83813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>9d26781a-262d-400a-85a2-2075aa4bd608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78de95d8-d59e-4558-ba9b-d54d84553647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama_istri&quot;)</value>
      <webElementGuid>56fb2f1b-6da2-463c-bff0-15bee8d96afb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama_istri']</value>
      <webElementGuid>b8912c1a-77c9-4073-aa95-23aeca8a875e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[4]/input</value>
      <webElementGuid>de22c865-bb4a-4672-b5dd-2711da18f9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>377e8321-acd2-49e5-bd3c-eb97bdd26af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_istri' and @id = 'nama_istri' and @placeholder = 'Nama Istri' and @type = 'text']</value>
      <webElementGuid>f4fc56b4-3cde-4efb-8cfa-1fafdd9fad75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
