<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KecamatanMOYUDANMINGGIRSEYEGANGODEAN_9010d9</name>
   <tag></tag>
   <elementGuidId>5e41fe5e-f738-4f9b-8a45-3c697d5a8a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>86b0ecc7-0230-47ca-8d29-b8d711581946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e8bf0560-6036-496b-b180-6ab594d59198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kec</value>
      <webElementGuid>a3fd6a4f-2578-4759-8d2b-c9590b056358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>225b19c2-c484-467d-8130-93e1412a3197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanMOYUDANMINGGIRSEYEGANGODEANGAMPINGMLATIDEPOKBERBAHPRAMBANANKALASANNGEMPLAKNGAGLIKSLEMANTEMPELTURIPAKEMCANGKRINGAN</value>
      <webElementGuid>bad4450c-a242-4003-8f10-d3daf96603b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kec&quot;)</value>
      <webElementGuid>c1c208c5-1287-4e6d-8b46-93292d15c4db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kec']</value>
      <webElementGuid>af3aa1e4-7ddb-494b-9766-9934d40818c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[2]/select</value>
      <webElementGuid>2005f04e-3034-4bf9-9510-21f9b8902767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[1]</value>
      <webElementGuid>a17957e7-34a9-478e-afda-207b46323cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[2]</value>
      <webElementGuid>9e36e4ef-0dd6-4446-aae9-349f932139c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>2576bcef-f3d9-4fb3-adc7-91ed43783c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[2]</value>
      <webElementGuid>caf25f89-1f81-41e6-aae3-038e6999982b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>3ddd753c-4839-4a67-9e2e-3d967b19b633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kec' and @name = 'Kecamatan' and (text() = 'KecamatanMOYUDANMINGGIRSEYEGANGODEANGAMPINGMLATIDEPOKBERBAHPRAMBANANKALASANNGEMPLAKNGAGLIKSLEMANTEMPELTURIPAKEMCANGKRINGAN' or . = 'KecamatanMOYUDANMINGGIRSEYEGANGODEANGAMPINGMLATIDEPOKBERBAHPRAMBANANKALASANNGEMPLAKNGAGLIKSLEMANTEMPELTURIPAKEMCANGKRINGAN')]</value>
      <webElementGuid>d08255c2-01b6-4ac1-916f-aee797823dc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
