<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KabupatenKABUPATEN BANTULKABUPATEN G_999db8</name>
   <tag></tag>
   <elementGuidId>bdd22faa-5ac2-46a2-9366-d658a773b71f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>73a708b2-b44c-4545-89af-b1886394feaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>41338873-755b-42c9-bf87-9806f6c928cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kab</value>
      <webElementGuid>85d97a00-4916-4ce6-9cf3-64a2bbe07cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kabupaten</value>
      <webElementGuid>429b8b85-5498-4432-9499-e9b508d063b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA</value>
      <webElementGuid>2e5f9c77-cc4f-4adf-82eb-6aea3abede9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kab&quot;)</value>
      <webElementGuid>7502f7f8-f112-4f80-85aa-9ed644293769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kab']</value>
      <webElementGuid>4ca907aa-376d-44bb-a29b-9404582e0468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div/select</value>
      <webElementGuid>e6ac313f-0678-4240-a3db-2e05cc14cf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[1]</value>
      <webElementGuid>b0f07b8f-5d15-4bbc-a21a-f515ddb7d82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi *'])[1]/following::select[2]</value>
      <webElementGuid>e0e6ef44-849f-4888-9632-062a71a39d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/preceding::select[1]</value>
      <webElementGuid>6de2866f-c357-4a94-93f1-28e4237bda1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[2]</value>
      <webElementGuid>adbed5c5-60ee-4086-a083-d12cd386cb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>79637084-899b-43d4-a4db-05cee12f2d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kab' and @name = 'Kabupaten' and (text() = 'KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA' or . = 'KabupatenKABUPATEN BANTULKABUPATEN GUNUNG KIDULKABUPATEN KULON PROGOKABUPATEN SLEMANKOTA YOGYAKARTA')]</value>
      <webElementGuid>be8f74e8-8f3f-46c2-906a-c399b54e29f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
