<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Desa  KelurahanCATUR HARJOPANDOWO HA_343a22</name>
   <tag></tag>
   <elementGuidId>d52ac647-a168-41ec-a526-996c5d35fd06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Desa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Desa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa712da1-c6e9-4ae0-aab2-c7c8cb735e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c141dc7b-4b8b-4896-a81e-fb35cab7994e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Desa</value>
      <webElementGuid>4fca938d-1faf-4d3f-af73-acc738fa1648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Desa_Kelurahan</value>
      <webElementGuid>3a03acaf-d8d0-4658-bc36-5b8be878270c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desa / KelurahanCATUR HARJOPANDOWO HARJOTRI MULYOTRIDADITRIHARJO</value>
      <webElementGuid>60025cea-ae1b-4449-910a-7ba6cd46165f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desa&quot;)</value>
      <webElementGuid>d1d67674-7d33-4e50-88cf-3f20648ea105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Desa']</value>
      <webElementGuid>8b0ba4e9-3bb3-4eea-bd51-1cacea956d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[3]/select</value>
      <webElementGuid>22224970-5558-4bfd-b4f9-20724e7ec89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/following::select[1]</value>
      <webElementGuid>0949a49e-46bd-4e35-92cb-4d4562086831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[2]</value>
      <webElementGuid>be9e2d10-d142-42be-a7b2-8afc1f8f8649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[1]</value>
      <webElementGuid>f701dc66-82aa-459c-b599-fda7aa3ff62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/preceding::select[1]</value>
      <webElementGuid>5d08feef-a166-4061-b6af-327c22c225e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/select</value>
      <webElementGuid>16f488b7-a148-48ee-82ab-d2f5999a8471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Desa' and @name = 'Desa_Kelurahan' and (text() = 'Desa / KelurahanCATUR HARJOPANDOWO HARJOTRI MULYOTRIDADITRIHARJO' or . = 'Desa / KelurahanCATUR HARJOPANDOWO HARJOTRI MULYOTRIDADITRIHARJO')]</value>
      <webElementGuid>e37917a6-aa1b-40f8-ac23-aefd10f872ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
