<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SD                                  _d31312</name>
   <tag></tag>
   <elementGuidId>3b8e8df6-25b9-40e7-a814-ac60b13c42d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;pendidikan_terakhir&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='pendidikan_terakhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c473f948-4ac0-4be0-8621-0417b3273be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0cf301ed-9444-422b-ba43-35bf87703725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pendidikan_terakhir</value>
      <webElementGuid>5252f834-dba9-4e04-8d8f-afe7c67027a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                </value>
      <webElementGuid>58883ed8-cdde-47aa-8911-437b6ce340a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>bf2ffdb8-6fcc-440b-b739-baa1750184fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='pendidikan_terakhir']</value>
      <webElementGuid>e9a4ebac-d01b-479a-9852-16e0f467e0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[3]/select</value>
      <webElementGuid>5386c995-ad95-4d20-bfc4-a55b63a4f284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/following::select[1]</value>
      <webElementGuid>fb25ee65-f71f-4e8a-811f-0098e2c2d425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/following::select[1]</value>
      <webElementGuid>5f1055c7-8e8a-4e15-a15b-9ea0ccdafd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Lahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>b07bae27-5969-4aaa-8561-887e39bca67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Tanggungan *'])[1]/preceding::select[1]</value>
      <webElementGuid>d937345d-bf0c-44a0-88c0-1f576ad0cac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>fd33e0c8-d0e8-4ed7-88a5-169270d819ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pendidikan_terakhir' and (text() = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ' or . = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ')]</value>
      <webElementGuid>c0e1ce2f-a40a-4348-abd7-364f4c2a1372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
