<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Laki-laki_jenis_kelamin</name>
   <tag></tag>
   <elementGuidId>24b286c3-2191-41b0-882a-54696134714c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#optionsRadiosLaki</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='optionsRadiosLaki']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>907a358e-a632-4843-a81c-59e4d30c6935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c3aa43da-e1ae-4bfb-95fb-f6010e085a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_kelamin</value>
      <webElementGuid>77544c92-5036-4a1b-b128-9651b422f157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>optionsRadiosLaki</value>
      <webElementGuid>1d77f609-ad9d-4b49-ad5d-964ac464831d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>46bef2f7-6526-4e8d-831b-36879ba12040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optionsRadiosLaki&quot;)</value>
      <webElementGuid>574a842f-a741-43a0-bbd6-be265f4a5055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='optionsRadiosLaki']</value>
      <webElementGuid>d990bba5-69f3-4d1e-b2d6-19d19c78af1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[11]/div/label/input</value>
      <webElementGuid>42a16553-dc9c-4086-84ab-6ec786185372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/label/input</value>
      <webElementGuid>793c9095-636b-4726-9329-a276a98bb805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'jenis_kelamin' and @id = 'optionsRadiosLaki']</value>
      <webElementGuid>8c983ba3-55a3-4d50-ab0b-0feb01837f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
