<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Islam                               _f363b0</name>
   <tag></tag>
   <elementGuidId>85d0f458-23dc-4582-8f15-c212a3dc0b35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;agama&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='agama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>585379e2-4642-4f3a-a7ec-f522340ec51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ddc24976-d3e1-4e8d-9028-0d7e4dc4c465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agama</value>
      <webElementGuid>14b71b9c-5613-48e6-bf34-58d58e5268d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                </value>
      <webElementGuid>c489d9f0-0cfe-45a0-afd0-a9813d62c727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>596e3ed7-b47a-4cdc-aaa4-1adef23fe6d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='agama']</value>
      <webElementGuid>d06dcae5-cf59-43f5-913b-3380dc823f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[8]/select</value>
      <webElementGuid>dfdb1a73-7610-44e0-99db-bac0f465a3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agama *'])[1]/following::select[1]</value>
      <webElementGuid>53a4a8cf-add9-47b8-b153-80e7aa897f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email *'])[1]/following::select[1]</value>
      <webElementGuid>671210b6-98d9-4a30-8978-58ce3d68813d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Keahlian *'])[1]/preceding::select[1]</value>
      <webElementGuid>a036412e-c7e3-4e3e-9bc2-2aaae9ae8fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Petani *'])[1]/preceding::select[1]</value>
      <webElementGuid>2489beeb-a99b-40fe-a3d5-619744e98359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>452779c0-9c72-4a4f-a26b-e553e01f7e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'agama' and (text() = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ' or . = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ')]</value>
      <webElementGuid>2c81158c-6259-4d11-ad1d-884d8f0e6c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
