<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk_username</name>
   <tag></tag>
   <elementGuidId>2f7d9c1c-67a6-4f69-95b6-458dedb8b174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel.panel-info > div.panel-body > div.input-group > #login-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='login-username'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23623685-25e5-4441-b5e2-1a2bed9fdeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-username</value>
      <webElementGuid>4bfee219-be6e-4f7f-88df-7b64d17b28ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>872dc0ca-0073-4382-8532-0c58d70e3af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>978dcd4f-a17a-46f2-9160-290cb5468d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>a79a96a9-9e28-485a-b064-1fd8ddd49970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ID Pengguna</value>
      <webElementGuid>40383681-5b7d-44fb-8ef4-13c47238fe28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main&quot;]/div[@class=&quot;col-md-push-3 col-md-6&quot;]/form[@id=&quot;loginform&quot;]/div[@class=&quot;panel panel-info&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;login-username&quot;]</value>
      <webElementGuid>75fc648e-fed8-4a57-b922-8de93abd342e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='login-username'])[2]</value>
      <webElementGuid>7242079e-edeb-4825-9076-419037e62c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/div/div[2]/div/input</value>
      <webElementGuid>b43326b2-3ffb-44cc-ac31-4f07d482bbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>584be90d-5eca-44db-bf16-68010cf4a67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-username' and @type = 'text' and @name = 'username' and @placeholder = 'ID Pengguna']</value>
      <webElementGuid>6c364880-4118-40bb-9146-c5d9f116d73d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
