<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk_password</name>
   <tag></tag>
   <elementGuidId>5a324a74-36c0-48ad-a75a-6b0b3b60c2e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel.panel-info > div.panel-body > div.input-group > #login-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='login-password'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b9f7d9a-91ec-4368-a183-14094d0218bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-password</value>
      <webElementGuid>58214218-8342-4f78-8e61-c313be506d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dbf024e6-4bdc-42d6-a114-f04daa144d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aa90cb1f-01de-40d6-a4ae-22143fcd5a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2c0f10c1-8d17-42e8-a972-f90cea1c4db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kata Kunci</value>
      <webElementGuid>b74dba85-2930-4786-97bd-ffe1fab86500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main&quot;]/div[@class=&quot;col-md-push-3 col-md-6&quot;]/form[@id=&quot;loginform&quot;]/div[@class=&quot;panel panel-info&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;login-password&quot;]</value>
      <webElementGuid>b7febfec-62e3-4b68-b91e-07cce090ebbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='login-password'])[2]</value>
      <webElementGuid>fca2cfd4-2ba2-4aab-9111-268cb1d14b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/div/div[2]/div[2]/input</value>
      <webElementGuid>4d6fa9ac-cd14-472f-a6c3-5b51f643200b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>dfd41e10-a5b4-41b7-97ce-b015c5285833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-password' and @type = 'password' and @name = 'password' and @placeholder = 'Kata Kunci']</value>
      <webElementGuid>5db85539-22d2-453f-865e-715d0458cb3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
